CREATE TABLE trading_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_name VARCHAR(50) NOT NULL,
    broker VARCHAR(100) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    balance NUMERIC(19, 4) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trading_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_trading_accounts_user_name UNIQUE (user_id, account_name),
    CONSTRAINT chk_trading_accounts_balance_non_negative CHECK (balance >= 0),
    CONSTRAINT chk_trading_accounts_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'))
);

CREATE INDEX idx_trading_accounts_user_id ON trading_accounts (user_id);
