CREATE TABLE account_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    balance_after NUMERIC(19, 4) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account_transactions_account FOREIGN KEY (account_id) REFERENCES trading_accounts (id) ON DELETE CASCADE,
    CONSTRAINT chk_account_transactions_type CHECK (type IN ('DEPOSIT', 'WITHDRAWAL')),
    CONSTRAINT chk_account_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_account_transactions_balance_non_negative CHECK (balance_after >= 0)
);

CREATE INDEX idx_account_transactions_account_created
    ON account_transactions (account_id, created_at DESC);
