ALTER TABLE account_transactions
    DROP CONSTRAINT chk_account_transactions_type;

ALTER TABLE account_transactions
    ADD CONSTRAINT chk_account_transactions_type
        CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRADE_BUY', 'TRADE_SELL'));

CREATE TABLE positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    quantity NUMERIC(19, 8) NOT NULL,
    average_price NUMERIC(19, 8) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_positions_account FOREIGN KEY (account_id) REFERENCES trading_accounts (id) ON DELETE CASCADE,
    CONSTRAINT uq_positions_account_symbol UNIQUE (account_id, symbol),
    CONSTRAINT chk_positions_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_positions_average_price_positive CHECK (average_price > 0)
);

CREATE TABLE trade_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    quantity NUMERIC(19, 8) NOT NULL,
    price NUMERIC(19, 8) NOT NULL,
    total_value NUMERIC(19, 4) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trade_orders_account FOREIGN KEY (account_id) REFERENCES trading_accounts (id) ON DELETE CASCADE,
    CONSTRAINT chk_trade_orders_side CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT chk_trade_orders_status CHECK (status = 'FILLED'),
    CONSTRAINT chk_trade_orders_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_trade_orders_price_positive CHECK (price > 0),
    CONSTRAINT chk_trade_orders_total_positive CHECK (total_value > 0)
);

CREATE INDEX idx_positions_account_id ON positions (account_id);
CREATE INDEX idx_trade_orders_account_created ON trade_orders (account_id, created_at DESC);
